name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'model.py'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate documentation
        run: |
          pip install pydoc-markdown
          mkdir -p docs
          pydoc-markdown --renderers markdown --loader python.path=model.py > docs/model.md

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/
